device_name = "CANShunt"
software_version = "v0.3.0"
hardware_version = "rev2"
heartbeat_period = 1000
autostart = "enabled"

[identity]
vendor_id = 0xCAFE
product_code = 1050
revision_number = 2

[pdos]
num_tpdo = 4

[pdos.tpdo.0]
enabled = true
cob_id = 0x200
add_node_id = false
transmission_type = 254
mappings = [
    { index=0x2010, sub=1, size=16 },
    { index=0x2010, sub=2, size=16 },
    { index=0x2010, sub=3, size=16 },
    { index=0x2010, sub=4, size=16 },
]
[pdos.tpdo.1]
enabled = true
cob_id = 0x201
add_node_id = false
transmission_type = 254
mappings = [
    { index=0x2010, sub=5, size=16 },
    { index=0x2010, sub=6, size=16 },
    { index=0x2010, sub=7, size=16 },
    { index=0x2010, sub=8, size=16 },
]
[pdos.tpdo.2]
enabled = true
cob_id = 0x202
add_node_id = false
transmission_type = 254
mappings = [
    { index=0x2011, sub=1, size=16 },
    { index=0x2011, sub=2, size=16 },
    { index=0x2011, sub=3, size=16 },
    { index=0x2011, sub=4, size=16 },
]
[pdos.tpdo.3]
enabled = true
cob_id = 0x203
add_node_id = false
transmission_type = 254
mappings = [
    { index=0x2011, sub=5, size=16 },
    { index=0x2011, sub=6, size=16 },
    { index=0x2011, sub=7, size=16 },
    { index=0x2011, sub=8, size=16 },
]

# The raw 12-bit ADC readings for current sensors
[[objects]]
index = 0x2000
parameter_name = "Raw INA183 Input"
object_type = "array"
data_type = "uint16"
access_type = "ro"
array_size = 8
pdo_mapping = "tpdo"

# The raw 12-bit ADC readings for voltage sensors
[[objects]]
index = 0x2001
parameter_name = "Raw Voltage Input"
object_type = "array"
data_type = "uint16"
access_type = "ro"
array_size = 8
pdo_mapping = "tpdo"

[[objects]]
index = 0x2010
parameter_name = "Current (mA)"
object_type = "array"
data_type = "uint16"
access_type = "ro"
array_size = 8
pdo_mapping = "tpdo"

[[objects]]
index = 0x2011
parameter_name = "Voltage (mV)"
object_type = "array"
data_type = "uint16"
access_type = "ro"
array_size = 8
pdo_mapping = "tpdo"

# Counts per 10A for INA sensors
[[objects]]
index = 0x2100
parameter_name = "Current Scale"
#description = "Current calibration factor. Factory set, but can be adjusted."
object_type = "var"
data_type = "uint16"
access_type = "rw"
default_value = 1943
persist = true

[[objects]]
index = 0x2200
parameter_name = "Bitrate Config"
#description = "0 - 1000k, 1 - 800k, 2 - 500k, 3 - 250k, 4 - 125k, 5 - 100k, 6 - 50k"
object_type = "var"
data_type = "uint8"
access_type = "rw"
default_value = 2
persist = true

[[objects]]
index = 0x2f80
parameter_name = "Identify Command"
object_type = "var"
data_type = "uint8"
access_type = "rw"
