device_name = "can-io"
software_version = "v0.0.1"
hardware_version = "rev1"
heartbeat_period = 1000

[identity]
vendor_id = 0xCAFE
product_code = 1033
revision_number = 1

[pdos]
num_tpdo = 4

[pdos.tpdo.0]
enabled = true
cob_id = 0x200
add_node_id = false
transmission_type = 254
mappings = [
    { index=0x2000, sub=1, size=16 },
    { index=0x2000, sub=2, size=16 },
    { index=0x2000, sub=3, size=16 },
    { index=0x2000, sub=4, size=16 },
]
[pdos.tpdo.1]
enabled = true
cob_id = 0x201
add_node_id = false
transmission_type = 254
mappings = [
    { index=0x2000, sub=5, size=16 },
    { index=0x2000, sub=6, size=16 },
    { index=0x2000, sub=7, size=16 },
    { index=0x2000, sub=8, size=16 },
]
[pdos.tpdo.2]
enabled = true
cob_id = 0x202
add_node_id = false
transmission_type = 254
mappings = [
    { index=0x2001, sub=1, size=16 },
    { index=0x2001, sub=2, size=16 },
    { index=0x2001, sub=3, size=16 },
    { index=0x2001, sub=4, size=16 },
]
[pdos.tpdo.3]
enabled = true
cob_id = 0x203
add_node_id = false
transmission_type = 254
mappings = [
    { index=0x2001, sub=5, size=16 },
    { index=0x2001, sub=6, size=16 },
    { index=0x2001, sub=7, size=16 },
    { index=0x2001, sub=8, size=16 },
]

# The raw 12-bit ADC readings
[[objects]]
index = 0x2000
parameter_name = "Raw INA183 Input"
object_type = "array"
data_type = "uint16"
access_type = "ro"
array_size = 8
pdo_mapping = "tpdo"

[[objects]]
index = 0x2001
parameter_name = "Raw ZXCT1110 Input"
object_type = "array"
data_type = "uint16"
access_type = "ro"
array_size = 8
pdo_mapping = "tpdo"

[[objects]]
index = 0x2010
parameter_name = "Current (mA)"
object_type = "array"
data_type = "uint16"
access_type = "ro"
array_size = 8
pdo_mapping = "tpdo"

# Counts per 10A for INA sensors
[[objects]]
index = 0x2100
parameter_name = "Current Scale"
object_type = "var"
data_type = "uint16"
access_type = "rw"
default_value = 2195
